import type { Producto } from "./types/General.type";

const usd = 415;
const margen = 0.3; // 30%

const precioFinal = (costo: number) => {
  const precioFinal = costo / (1 - margen);
  return precioFinal / usd;
};

export const productos: Producto[] = [
  {
    id: 1,
    nombre: "Flan de Leche",
    description:
      "Exquisito Flan de Leche elaborado a base de huevos, leche y azúcar.",
    precio: 5,
    image: "flan.jpeg",
    categoria: "Varios",
    alias: "flan-de-leche",
    agotado: true,
  },
  {
    id: 2,
    nombre: "Aceite 1 Litro",
    precio: 2.6,
    description: "",
    image: "haysa1l.jpg",
    categoria: "Varios",
    alias: "aceite",
    agotado: false,
  },
  {
    id: 3,
    nombre: "Pollo 10 LB",
    description: "",
    precio: 12,
    image: "pollo10lb.jpg",
    categoria: "Carnícos",
    alias: "pollo-10-lb",
    agotado: false,
  },
  {
    id: 4,
    nombre: "Salchicha 3KG",
    description: "",
    precio: 9,
    image: "salchicha3kg.jpg",
    categoria: "Carnícos",
    alias: "salchicha-3kg",
    agotado: false,
  },
  {
    id: 5,
    nombre: "Leche 1KG",
    description: "",
    precio: 7.99,
    image: "bartex.jpg",
    categoria: "Lácteos",
    alias: "leche",
    agotado: false,
  },
  {
    id: 6,
    nombre: "Huevos (30)",
    precio: 8.8,
    description: "30 Huevos",
    image: "huevos.webp",
    categoria: "Varios",
    alias: "huevos",
    agotado: false,
  },
  {
    id: 7,
    nombre: "Frijoles 1 KG",
    precio: 2.7,
    description: "",
    image: "frijoles1kg.jpg",
    categoria: "Granos",
    alias: "frijoles-1-kg",
    agotado: false,
  },

  {
    id: 9,
    nombre: "Azúcar",
    precio: 1.99,
    description: "Paquetico sellado de azúcar de 1kg",
    image: "azucar.jpg",
    categoria: "Varios",
    alias: "azucar",
    agotado: false,
  },
  {
    id: 10,
    nombre: "Arroz",
    precio: 1.7,
    description: "Paquetico sellado de arroz de 1kg",
    image: "arroz.jpg",
    categoria: "Varios",
    alias: "arroz",
    agotado: false,
  },
  {
    id: 11,
    nombre: "Malta Perla",
    precio: 0.9,
    description: "Malta Perla producida en la Cervecería Bucanero en Holguín",
    image: "maltaperla.jpg",
    categoria: "Bebidas",
    alias: "malta-perla",
    agotado: true,
  },
  {
    id: 12,
    nombre: "Spaguettis",
    precio: 0.9,
    description: "",
    image: "spaguettis500.jpg",
    categoria: "Pastas",
    alias: "spaguettis",
    agotado: false,
  },
  {
    id: 13,
    nombre: "Leche Condensada",
    precio: 1.5,
    description: "Latica de leche condensada 390 g",
    image: "Leche-Condensada-390g.jpg",
    categoria: "Lácteos",
    alias: "leche-condensada",
    agotado: false,
  },
  {
    id: 14,
    nombre: "Leche Condensada Hervida",
    precio: 1.8,
    description: "Latica de leche condensada hervida casera 390 g",
    image: "lechehervida.jpg",
    categoria: "Lácteos",
    alias: "leche-condensada-hervida",
    agotado: false,
  },
  {
    id: 15,
    nombre: "Queso Gouda 1Lb",
    precio: 5.1,
    description:
      "Queso de primera calidad ideal para spaguettis , pizzas o bocaditos",
    image: "queso-gouda_3.webp",
    categoria: "Lácteos",
    alias: "queso-gouda-1lb",
    agotado: false,
  },
  {
    id: 16,
    nombre: "Latica Pure Vima",
    precio: 1.65,
    description: "Pure Vima buen rendimiento y calidad",
    image: "vima.webp",
    categoria: "Varios",
    alias: "pure-vima",
    agotado: false,
  },
  {
    id: 17,
    nombre: "Galletas Saltitacos",
    precio: 3.37,
    description: "El pqt trae 7 paqueticos ideales para las meriendas",
    image: "saltitacos.jpg",
    categoria: "Varios",
    alias: "saltitacos",
    agotado: false,
  },
  {
    id: 18,
    nombre: "Jugo Manzana",
    precio: 0.68,
    description: "Jugo de Manzana 200 ml Badelli",
    image: "manzanabadelli.jpg",
    categoria: "Bebidas",
    alias: "manzana-badelli",
    agotado: true,
  },
  {
    id: 19,
    nombre: "Cerveza Cristal",
    precio: 0.75,
    description: "La preferida de Cuba",
    image: "cristal.jpg",
    categoria: "Bebidas",
    alias: "cerveza-cristal",
    agotado: false,
  },
  {
    id: 20,
    nombre: "Jugo Guayaba",
    precio: 0.68,
    description: "Cajita de 200 ml",
    image: "guayaba20ml.jpg",
    categoria: "Bebidas",
    alias: "jugo-guayaba-200ml",
    agotado: true,
  },
  {
    id: 21,
    nombre: "Galletas de leche",
    precio: 2.1,
    description: "Galleticas con sabor a leche incluye 8 paqueticos",
    image: "milkRedonda.webp",
    categoria: "Confituras",
    alias: "galleticas-milk",
    agotado: false,
  },
  {
    id: 22,
    nombre: "Refresco Pomo 1.5 L",
    precio: 2.2,
    description: "Sabor Naranja",
    image: "naranja1.5l.jpg",
    categoria: "Bebidas",
    alias: "pomo-naranja",
    agotado: false,
  },
  {
    id: 23,
    nombre: "Galleticas Mantequilla",
    precio: 2.1,
    description: "Sabor mantequilla 8 paqueticos",
    image: "buttercookies.jpg",
    categoria: "Confituras",
    alias: "galleticas-mantequilla",
    agotado: false,
  },
  {
    id: 24,
    nombre: "Nectar de Pera",
    precio: 0.99,
    description: "Jugo de Pera Enlatado 330 ml",
    image: "lata-pera.webp",
    categoria: "Bebidas",
    alias: "jugo-lata-pera",
    agotado: false,
  },
  {
    id: 25,
    nombre: "Yogurt Fresa (4u)",
    precio: 2.69,
    description: "Pack 4 unidades potecitos de 100g",
    image: "yogurt-fresa-vima.webp",
    categoria: "Lácteos",
    alias: "yogurt-fresa-vima",
    agotado: false,
  },
  {
    id: 26,
    nombre: "Pasta Dental Bambú",
    precio: 1.23,
    description: "100g sabor mentolado",
    image: "pasta-bambu.webp",
    categoria: "Aseo",
    alias: "pasta-bambu",
    agotado: false,
  },
  {
    id: 27,
    nombre: "Galletas María",
    precio: 1.1,
    description: "Galleticas Dulces",
    image: "galletasMaria.jpg",
    categoria: "Confituras",
    alias: "galletas-maria",
    agotado: false,
  },
  {
    id: 28,
    nombre: "Peter Milano",
    precio: 0.6,
    description: "Peter Italiano",
    image: "peter-milano.jpg",
    categoria: "Confituras",
    alias: "peter-milano",
    agotado: false,
  },
  {
    id: 29,
    nombre: "Detergente Polvo",
    precio: 0.9,
    description: "Detergente Rayan 400g de Limón",
    image: "detergente-rayan.jpg",
    categoria: "Aseo",
    alias: "detergente-rayan",
    agotado: false,
  },
  {
    id: 30,
    nombre: "Papel Sanitario",
    precio: 1.8,
    description: "4 rollos de papel sanitario",
    image: "papel-laexelencia.jpg",
    categoria: "Aseo",
    alias: "papel-laexelencia",
    agotado: false,
  },
  {
    id: 31,
    nombre: "Jabón de Baño",
    precio: 0.55,
    description: "Jabón de Carbón 100g",
    image: "jabon-carbon.jpg",
    categoria: "Aseo",
    alias: "jabon-carbon",
    agotado: false,
  },
  {
    id: 32,
    nombre: "Jabón de Lavar",
    precio: 0.9,
    description: "Barra 200g",
    image: "jabon-lavar-flash.webp",
    categoria: "Aseo",
    alias: "jabon-lavar-flash",
    agotado: false,
  },
  {
    id: 33,
    nombre: "Jugo Manzana",
    precio: 0.68,
    description: "Jugo de Manzana 200 ml La Estancia",
    image: "manzana-laestancia.webp",
    categoria: "Bebidas",
    alias: "manzana-laestancia",
    agotado: false,
  },
  {
    id: 34,
    nombre: "Bolsa de Pan (10u)",
    precio: 0.8,
    description: "10 panes de bola",
    image: "bolsa-pan.jpg",
    categoria: "Varios",
    alias: "bolsa-pan",
    agotado: false,
  },
  {
    id: 35,
    nombre: "Coditos",
    precio: 0.8,
    description: "Paquete de 500g",
    image: "coditos-doga.webp",
    categoria: "Pastas",
    alias: "coditos-doga",
    agotado: false,
  },
  {
    id: 36,
    nombre: "Refresco Enlatado",
    precio: 0.75,
    description: "Sabores : Cola,Naranja,otros según disponibilidad",
    image: "ritz-cola.jpg",
    categoria: "Bebidas",
    alias: "refresco-lata-ritz",
    agotado: false,
  },
    {
    id: 37,
    nombre: "Lomo de Cerdo 1 LB",
    precio: 3.15,
    description: "No contiene huesos, ni gordo",
    image: "lomo-cerdo.jpg",
    categoria: "Carnícos",
    alias: "lomo-cerdo",
    agotado: false,
  },
     {
    id: 38,
    nombre: "Caja Mayabe 24u",
    precio: 16.90,
    description: "24 unidades de Mayabe",
    image: "mayabe_1.png",
    categoria: "Bebidas",
    alias: "caja-mayabe",
    agotado: false,
  },
    {
    id: 39,
    nombre: "Caja Cristal 24u",
    precio: 16.90,
    description: "24 unidades de Cristal de Lata",
    image: "caja-cristal.webp",
    categoria: "Bebidas",
    alias: "caja-cristal",
    agotado: false,
  },
];
